eclinic/api/urls.py
from django.urls import path, re_path
from django.views.decorators.csrf import csrf_exempt
from . import views

app_name='api'

urlpatterns = [
    path('getStatesByCountry', csrf_exempt(views.getStatesByCountry), name='getStatesByCountry'),
    path('getCitiesByState', csrf_exempt(views.getCitiesByState), name='getCitiesByState'),
]

eclinic/eclinic/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve

urlpatterns = [
    path('', include('front.urls')),
    path('admin/', include('superadmin.urls')),
    path('api/', include('api.urls')),
    # path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

handler404 = 'eclinic.views.custom_page_not_found_view'
handler500 = 'eclinic.views.custom_error_view'
handler403 = 'eclinic.views.custom_permission_denied_view'
handler400 = 'eclinic.views.custom_bad_request_view'

eclinic/front/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Permission
from .managers import UserManager
from django.utils.timezone import now
from django.core.validators import RegexValidator
from django.utils.text import gettext_lazy as _


class Role(models.Model):
    name = models.CharField(max_length=20)
    status = models.SmallIntegerField(default=1)
    deleted = models.BooleanField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'role'
        verbose_name_plural = 'role'


class User(AbstractUser):
    phone = models.CharField(
        verbose_name='phone number',
        max_length=15,
        unique=True,
        error_messages={
            'unique': 'A user with that phone number already exists.'},
        help_text='Required. 15 characters or fewer',
    )
    email = models.EmailField(
        verbose_name='email address',
        max_length=150,
        unique=True,
        error_messages={'unique': 'A user with that email already exists.'},
        help_text='Required. 150 characters or fewer. Letters, digits and @/./_ only.',
    )
    name = models.CharField(max_length=200, blank=True, null=True)
    pswd_token = models.CharField(max_length=255, blank=True, null=True)
    role = models.ForeignKey(
        Role, related_name='userRole', on_delete=models.CASCADE, blank=True, null=True)

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = ['name', 'email']

    manager = UserManager()

    def __str__(self):
        return self.name

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_superuser

    class Meta:
        managed = True
        db_table = 'user'
        verbose_name_plural = 'user'


class RolePermission(models.Model):
    role = models.ForeignKey(Role, related_name='RolePermission',
                             on_delete=models.CASCADE, blank=True, null=True)
    permission = models.ForeignKey(
        Permission, related_name='PermissionRole', on_delete=models.CASCADE, blank=True, null=True)
    permitted = models.SmallIntegerField(default=0)
    status = models.SmallIntegerField(default=1)
    deleted = models.BooleanField(default=0)

    def __str__(self):
        return self.role.name + "=>" + self.permission.codename

    class Meta:
        managed = True
        db_table = 'role_permissions'
        verbose_name_plural = 'role_permissions'


class Country(models.Model):
    sortname = models.CharField(max_length=3)
    name = models.CharField(max_length=150)
    phonecode = models.CharField(max_length=5, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'country'
        verbose_name_plural = 'country'


class State(models.Model):
    name = models.CharField(max_length=30)
    country = models.ForeignKey(
        Country, related_name='CountryState', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'state'
        verbose_name_plural = 'state'


class City(models.Model):
    name = models.CharField(max_length=30)
    state = models.ForeignKey(
        State, related_name='StateCity', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'city'
        verbose_name_plural = 'city'


class Gender(models.Model):
    name = models.CharField(max_length=15)
    status = models.SmallIntegerField(default=1)
    deleted = models.BooleanField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'gender'
        verbose_name_plural = 'gender'


class Specialization(models.Model):
    name = models.CharField(max_length=15)
    status = models.SmallIntegerField(default=1)
    deleted = models.BooleanField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'specialization'
        verbose_name_plural = 'specialization'


class BloodGroup(models.Model):
    name = models.CharField(max_length=15)
    status = models.SmallIntegerField(default=1)
    deleted = models.BooleanField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'blood_group'
        verbose_name_plural = 'blood_group'


class Language(models.Model):
    name = models.CharField(max_length=15)
    status = models.SmallIntegerField(default=1)
    deleted = models.BooleanField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'language'
        verbose_name_plural = 'language'


class DoctorDetail(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    profile_pic = models.CharField(max_length=255, blank=True, null=True)
    gender = models.ForeignKey(
        Gender, on_delete=models.CASCADE, blank=True, null=True)
    specialization = models.ForeignKey(
        Specialization, on_delete=models.CASCADE, blank=True, null=True)
    dob = models.DateField(blank=True, null=True)
    blood_group = models.ForeignKey(
        BloodGroup, on_delete=models.CASCADE, blank=True, null=True)
    address = models.CharField(max_length=50, blank=True, null=True)
    locality = models.CharField(max_length=50, blank=True, null=True)
    pin = models.CharField(max_length=6, validators=[
                           RegexValidator('^[0-9]{6}$', _('Invalid Pin Number'))])
    country = models.ForeignKey(
        Country, on_delete=models.CASCADE, blank=True, null=True)
    state = models.ForeignKey(
        State, on_delete=models.CASCADE, blank=True, null=True)
    city = models.ForeignKey(
        City, on_delete=models.CASCADE, blank=True, null=True)
    alternate_number = models.CharField(max_length=15, blank=True, null=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, blank=True, null=True)
    status = models.SmallIntegerField(default=1)
    deleted = models.BooleanField(default=0)

    class Meta:
        managed = True
        db_table = 'doctor_detail'
        verbose_name_plural = "doctor_detail"

eclinic/templates/back/doctor/list.html
{% extends "back/base.html" %}
{% load static %}
{% load template_func %}

{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">
    
        <!-- Page Header -->
        <div class="page-header">
            <div class="row">
                <div class="col-sm-12">
                    <h3 class="page-title">Doctors List</h3>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Doctor List</li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /Page Header -->
        
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row mb-3">
                            <div class="col-lg-6">
                                <form method="GET" id="search_form">
                                    <div class="search">
                                        <input type="text" class="form-control key_search" name="keyword" value="{{ request.GET.keyword }}" placeholder="Search Here">
                                        <button class="btn btn-primary" type="submit">Search</button>
                                    </div>
                                </form>
                            </div>
                            {% if request.user.is_superuser == 1 or 'add_doctordetail'|get_session_permission:request is not None %}
                            <div class="col-md-6">
                                <div class="float-right">
                                    <a href="{% url 'doctorAdd' %}" class="btn btn-primary btn-sm">Add</a>
                                </div>
                            </div>
                            {% endif %}
                        </div>
                        <div class="table-responsive">
                            <table class="datatable table table-hover table-center mb-0">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Speciality</th>
                                        <th>Address</th>
                                        <th>Phone Number</th>
                                        <th>Language</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for each in result %}
                                    <tr>
                                        <td>
                                            <h2 class="table-avatar">
                                                <a href="#" class="avatar avatar-sm mr-2"><img class="avatar-img rounded-circle" src="{{each.doctordetail_set.all.0.profile_pic}}" alt="User Image"></a>
                                                <a href="#">{{each.name}}</a>
                                            </h2>
                                        </td>
                                        <td>{{each.doctordetail_set.all.0.specialization.name}}</td>
                                        
                                        <td>{{each.doctordetail_set.all.0.address}}<br/>{{each.doctordetail_set.all.0.locality}}</td>

                                        <td>{{each.phone}}</td>
                                        
                                        <td>
                                            {{each.doctordetail_set.all.0.language.name}}
                                        </td>

                                        <td>
                                            <a href="{% url 'doctorEdit' each.id %}" class="btn btn-info btn-sm">
                                                Edit </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>			
        </div>
        
    </div>			
</div>
{% endblock %}

{% block js %}
<script>
    // var timer;
    // $(document).on('keyup', '.key_search', function () {
    //     timer && clearTimeout(timer);
    //     timer = setTimeout(function () {
    //         $("#search_form").submit();
    //     }, 300);
    // });
</script>
{% endblock %}